export default [
  {
    name: 'Lancet-2',
    pic: ['Medic2-1.png'],
    alt: 'Lancet-2',
    logo: 'logo_rhodes',
    job: '医疗',
    num: 'RCX2',
    r: 1,
    pool: 2,
    sex: 0,
    tags: ['远程位', '治疗'],
    desc: '恢复友方单位生命，且不受<@ba.kw>部署数量</>限制，但再部署时间极长',
  },
  {
    name: 'Castle-3',
    pic: ['Cast3-1.png', 'Cast3-summer-1.png'],
    alt: 'Castle-3',
    logo: 'logo_rhodes',
    job: '近卫',
    num: 'RCX3',
    r: 1,
    pool: 2,
    sex: 1,
    tags: ['近战位', '支援'],
    desc: '能够阻挡一个敌人，且不受<@ba.kw>部署数量</>限制，但再部署时间极长',
  },
  {
    name: '夜刀',
    pic: ['Nblade-1.png'],
    alt: 'Yato',
    logo: 'logo_rhodes',
    job: '先锋',
    num: 'A41',
    r: 2,
    pool: 2,
    sex: 0,
    tags: ['近战位', '新手'],
    desc: '能够阻挡两个敌人',
  },
  {
    name: '黑角',
    pic: ['Noirc-1.png'],
    alt: 'Noir Corne',
    logo: 'logo_rhodes',
    job: '重装',
    num: 'A43',
    r: 2,
    pool: 2,
    sex: 1,
    tags: ['近战位', '新手'],
    desc: '能够阻挡三个敌人',
  },
  {
    name: '巡林者',
    pic: ['Rang-1.png'],
    alt: 'Rangers',
    logo: 'logo_rhodes',
    job: '狙击',
    num: 'A42',
    r: 2,
    pool: 2,
    sex: 1,
    tags: ['远程位', '新手'],
    desc: '优先攻击空中单位',
  },
  {
    name: '杜林',
    pic: ['Durin-1.png'],
    alt: 'Durin',
    logo: 'logo_rhodes',
    job: '术师',
    num: 'A44',
    r: 2,
    pool: 2,
    sex: 0,
    tags: ['远程位', '新手'],
    desc: '攻击造成<@ba.kw>法术伤害</>',
  },
  {
    name: '12F',
    pic: ['12fce-1.png'],
    alt: '12F',
    logo: 'logo_rhodes',
    job: '术师',
    num: 'R303',
    r: 2,
    pool: 2,
    sex: 1,
    tags: ['远程位', '新手'],
    desc: '攻击造成<@ba.kw>群体法术伤害</>',
  },
  {
    name: '芬',
    pic: ['Fang-1.png', 'Fang-winter-1.png'],
    alt: 'Fang',
    logo: 'logo_rhodes',
    job: '先锋',
    num: 'PA11',
    r: 3,
    pool: 3,
    sex: 0,
    tags: ['近战位', '费用回复'],
    desc: '能够阻挡两个敌人',
  },
  {
    name: '香草',
    pic: ['Wyvern-1.png'],
    alt: 'Vanilla',
    logo: 'logo_rhodes',
    job: '先锋',
    num: 'BS04',
    r: 3,
    pool: 3,
    sex: 0,
    tags: ['近战位', '费用回复'],
    desc: '能够阻挡两个敌人',
  },
  {
    name: '翎羽',
    pic: ['Falco-1.png'],
    alt: 'Plume',
    logo: 'logo_Laterano',
    job: '先锋',
    num: 'LT05',
    r: 3,
    pool: 3,
    sex: 0,
    tags: ['近战位', '输出', '费用回复'],
    desc: '击杀敌人后获得1点部署费用，撤退时返还初始部署费用',
  },
  {
    name: '玫兰莎',
    pic: ['Melan-1.png', 'Melan-epoque-1.png'],
    alt: 'Melantha',
    logo: 'logo_rhodes',
    job: '近卫',
    num: 'PA41',
    r: 3,
    pool: 3,
    sex: 0,
    tags: ['近战位', '输出', '生存'],
    desc: '能够阻挡一个敌人',
  },
  {
    name: '泡普卡',
    pic: ['Popka-1.png'],
    alt: 'Popukar',
    logo: 'logo_rhodes',
    job: '近卫',
    num: 'PA65',
    r: 3,
    pool: 1,
    sex: 0,
    tags: ['近战位', '群攻', '生存'],
    desc: '同时攻击阻挡的<@ba.kw>所有敌人</>',
  },
  {
    name: '卡缇',
    pic: ['Ardign-1.png'],
    alt: 'Cardigan',
    logo: 'logo_rhodes',
    job: '重装',
    num: 'PA45',
    r: 3,
    pool: 1,
    sex: 0,
    tags: ['近战位', '防护'],
    desc: '能够阻挡三个敌人',
  },
  {
    name: '米格鲁',
    pic: ['Beagle-1.png'],
    alt: 'Beagle',
    logo: 'logo_rhodes',
    job: '重装',
    num: 'PA14',
    r: 3,
    pool: 3,
    sex: 0,
    tags: ['近战位', '防护'],
    desc: '能够阻挡三个敌人',
  },
  {
    name: '斑点',
    pic: ['Spot-1.png', 'Spot-otaku-1.png'],
    alt: 'Spot',
    logo: 'logo_rhodes',
    job: '重装',
    num: 'PA64',
    r: 3,
    pool: 1,
    sex: 1,
    tags: ['近战位', '防护', '治疗'],
    desc: '技能可以治疗友方单位',
  },
  {
    name: '克洛丝',
    pic: ['Kroos-1.png'],
    alt: 'Kroos',
    logo: 'logo_rhodes',
    job: '狙击',
    num: 'PA12',
    r: 3,
    pool: 3,
    sex: 0,
    tags: ['远程位', '输出'],
    desc: '优先攻击空中单位',
  },
  {
    name: '安德切尔',
    pic: ['Adnach-1.png'],
    alt: 'Adnachiel',
    logo: 'logo_rhodes',
    job: '狙击',
    num: 'PA44',
    r: 3,
    pool: 2,
    sex: 1,
    tags: ['远程位', '输出'],
    desc: '优先攻击空中单位',
  },
  {
    name: '炎熔',
    pic: ['Lava-1.png'],
    alt: 'Lava',
    logo: 'logo_rhodes',
    job: '术师',
    num: 'PA15',
    r: 3,
    pool: 3,
    sex: 0,
    tags: ['远程位', '群攻'],
    desc: '攻击造成<@ba.kw>群体法术伤害</>',
  },
  {
    name: '芙蓉',
    pic: ['Hibisc-1.png', 'Hibisc-nian-1.png'],
    alt: 'Hibiscus',
    logo: 'logo_rhodes',
    job: '医疗',
    num: 'PA13',
    r: 3,
    pool: 3,
    sex: 0,
    tags: ['远程位', '治疗'],
    desc: '恢复友方单位生命',
  },
  {
    name: '安赛尔',
    pic: ['Ansel-1.png', 'Ansel-summer-1.png'],
    alt: 'Ansel',
    logo: 'logo_rhodes',
    job: '医疗',
    num: 'PA43',
    r: 3,
    pool: 3,
    sex: 1,
    tags: ['远程位', '治疗'],
    desc: '恢复友方单位生命',
  },
  {
    name: '史都华德',
    pic: ['Stward-1.png'],
    alt: 'Steward',
    logo: 'logo_rhodes',
    job: '术师',
    num: 'PA42',
    r: 3,
    pool: 3,
    sex: 1,
    tags: ['远程位', '输出'],
    desc: '攻击造成<@ba.kw>法术伤害</>',
  },
  {
    name: '梓兰',
    pic: ['Orchid-1.png'],
    alt: 'Orchid',
    logo: 'logo_rhodes',
    job: '辅助',
    num: 'PA61',
    r: 3,
    pool: 3,
    sex: 0,
    tags: ['远程位', '减速'],
    desc: '攻击造成<@ba.kw>法术伤害</>，并对敌人造成短暂的<@ba.kw>停顿</>',
  },
  {
    name: '夜烟',
    pic: ['Nights-1.png', 'Nights-3.png'],
    alt: 'Haze',
    logo: 'logo_victoria',
    job: '术师',
    num: 'VC02',
    r: 4,
    pool: 3,
    sex: 0,
    tags: ['远程位', '输出', '削弱'],
    desc: '攻击造成<@ba.kw>法术伤害</>',
  },
  {
    name: '远山',
    pic: ['Fmout-1.png', 'Fmout-3.png'],
    alt: 'Gitano',
    logo: 'logo_rhodes',
    job: '术师',
    num: 'SI01',
    r: 4,
    pool: 3,
    sex: 0,
    tags: ['远程位', '群攻'],
    desc: '攻击造成<@ba.kw>群体法术伤害</>',
  },
  {
    name: '格雷伊',
    pic: ['Greyy-1.png', 'Greyy-3.png'],
    alt: 'Greyy',
    logo: 'logo_rhodes',
    job: '术师',
    num: 'R119',
    r: 4,
    pool: 1,
    sex: 1,
    tags: ['远程位', '群攻', '减速'],
    desc: '攻击造成<@ba.kw>群体法术伤害</>',
  },
  {
    name: '杰西卡',
    pic: ['Jesica-1.png', 'Jesica-3.png', 'Jesica-sweep-1.png'],
    alt: 'Jessica',
    logo: 'logo_blacksteel',
    job: '狙击',
    num: 'BS03',
    r: 4,
    pool: 3,
    sex: 0,
    tags: ['远程位', '输出', '生存'],
    desc: '优先攻击空中单位',
  },
  {
    name: '流星',
    pic: ['Shotst-1.png', 'Shotst-3.png'],
    alt: 'Meteor',
    logo: 'logo_kazimierz',
    job: '狙击',
    num: 'ST02',
    r: 4,
    pool: 3,
    sex: 0,
    tags: ['远程位', '输出', '削弱'],
    desc: '优先攻击空中单位',
  },
  {
    name: '红云',
    pic: ['Clour-1.png', 'Clour-3.png'],
    alt: 'Vermeil',
    logo: 'logo_rhodes',
    job: '狙击',
    num: 'R122',
    r: 4,
    pool: 1,
    sex: 0,
    tags: ['远程位', '输出'],
    desc: '优先攻击空中单位',
  },
  {
    name: '白雪',
    pic: ['Yuki-1.png', 'Yuki-3.png'],
    alt: 'ShiraYuki',
    logo: 'logo_lungmen',
    job: '狙击',
    num: 'LM10',
    r: 4,
    pool: 3,
    sex: 0,
    tags: ['远程位', '群攻', '减速'],
    desc: '攻击造成<@ba.kw>群体物理伤害</>',
  },
  {
    name: '讯使',
    pic: ['Blackd-1.png', 'Blackd-3.png', 'Blackd-winter-1.png'],
    alt: 'Courier',
    logo: 'logo_kjerag',
    job: '先锋',
    num: 'JC04',
    r: 4,
    pool: 4,
    sex: 1,
    tags: ['近战位', '费用回复', '防护'],
    desc: '能够阻挡两个敌人',
  },
  {
    name: '清道夫',
    pic: ['Scave-1.png', 'Scave-3.png'],
    alt: 'Scavenger',
    logo: 'logo_rhodes',
    job: '先锋',
    num: 'SW02',
    r: 4,
    pool: 3,
    sex: 0,
    tags: ['近战位', '费用回复', '输出'],
    desc: '能够阻挡两个敌人',
  },
  {
    name: '红豆',
    pic: ['Vigna-1.png', 'Vigna-3.png', 'Vigna-summer-1.png'],
    alt: 'Vigna',
    logo: 'logo_rhodes',
    job: '先锋',
    num: 'R105',
    r: 4,
    pool: 3,
    sex: 0,
    tags: ['近战位', '输出', '费用回复'],
    desc: '击杀敌人后获得1点部署费用，撤退时返还初始部署费用',
  },
  {
    name: '桃金娘',
    pic: ['Myrtle-1.png', 'Myrtle-3.png'],
    alt: 'Myrtle',
    logo: 'logo_rhodes',
    job: '先锋',
    num: 'R108',
    r: 4,
    pool: 1,
    sex: 0,
    tags: ['近战位', '费用回复', '治疗'],
    desc: '技能发动期间阻挡数变为0',
  },
  {
    name: '杜宾',
    pic: ['Doberm-1.png', 'Doberm-3.png'],
    alt: 'Dobermann',
    logo: 'logo_rhodes',
    job: '近卫',
    num: 'R100',
    r: 4,
    pool: 3,
    sex: 0,
    tags: ['近战位', '输出', '支援'],
    desc: '可以攻击到<@ba.kw>较远敌人</>',
  },
  {
    name: '缠丸',
    pic: ['Gyuki-1.png', 'Gyuki-3.png'],
    alt: 'Matoimaru',
    logo: 'logo_rhodes',
    job: '近卫',
    num: 'HK01',
    r: 4,
    pool: 3,
    sex: 0,
    tags: ['近战位', '生存', '输出'],
    desc: '能够阻挡一个敌人',
  },
  {
    name: '霜叶',
    pic: ['Frostl-1.png', 'Frostl-3.png'],
    alt: 'Frostleaf',
    logo: 'logo_rhodes',
    job: '近卫',
    num: 'R123',
    r: 4,
    pool: 3,
    sex: 0,
    tags: ['近战位', '减速', '输出'],
    desc: '可以进行<@ba.kw>远程攻击</>，但此时攻击力降低至80%',
  },
  {
    name: '艾丝黛尔',
    pic: ['Estell-1.png', 'Estell-3.png'],
    alt: 'Estelle',
    logo: 'logo_rhodes',
    job: '近卫',
    num: 'IU04',
    r: 4,
    pool: 2,
    sex: 0,
    tags: ['近战位', '群攻', '生存'],
    desc: '同时攻击阻挡的<@ba.kw>所有敌人</>',
  },
  {
    name: '慕斯',
    pic: ['Frncat-1.png', 'Frncat-3.png'],
    alt: 'Mousse',
    logo: 'logo_victoria',
    job: '近卫',
    num: 'VC04',
    r: 4,
    pool: 3,
    sex: 0,
    tags: ['近战位', '输出'],
    desc: '攻击造成<@ba.kw>法术伤害</>',
  },
  {
    name: '砾',
    pic: ['Gravel-1.png', 'Gravel-3.png'],
    alt: 'Gravel',
    logo: 'logo_kazimierz',
    job: '特种',
    num: 'KZ04',
    r: 4,
    pool: 3,
    sex: 0,
    tags: ['近战位', '快速复活', '防护'],
    desc: '再部署时间大幅度<@ba.kw>减少</>',
  },
  {
    name: '暗索',
    pic: ['Rope-1.png', 'Rope-3.png'],
    alt: 'Rope',
    logo: 'logo_rim',
    job: '特种',
    num: 'RB02',
    r: 4,
    pool: 3,
    sex: 0,
    tags: ['近战位', '位移'],
    desc: '技能可以使敌人产生<@ba.kw>位移</>\n可以放置于远程位',
  },
  {
    name: '末药',
    pic: ['Myrrh-1.png', 'Myrrh-3.png', 'Myrrh-wild-1.png'],
    alt: 'Myrrh',
    logo: 'logo_rhodes',
    job: '医疗',
    num: 'R104',
    r: 4,
    pool: 3,
    sex: 0,
    tags: ['远程位', '治疗'],
    desc: '恢复友方单位生命',
  },
  {
    name: '嘉维尔',
    pic: ['Ccheal-1.png', 'Ccheal-3.png'],
    alt: 'Gavial',
    logo: 'logo_rhodes',
    job: '医疗',
    num: 'IU07',
    r: 4,
    pool: 0,
    sex: 0,
    tags: ['远程位', '治疗'],
    desc: '恢复友方单位生命',
  },
  {
    name: '苏苏洛',
    pic: ['Susuro-1.png', 'Susuro-3.png'],
    alt: 'Sussurro',
    logo: 'logo_rhodes',
    job: '医疗',
    num: 'R107',
    r: 4,
    pool: 1,
    sex: 0,
    tags: ['远程位', '治疗'],
    desc: '恢复友方单位生命',
  },
  {
    name: '调香师',
    pic: ['Flower-1.png', 'Flower-3.png', 'Flower-daily-1.png'],
    alt: 'Perfumer',
    logo: 'logo_rhodes',
    job: '医疗',
    num: 'MN03',
    r: 4,
    pool: 3,
    sex: 0,
    tags: ['远程位', '治疗'],
    desc: '同时恢复三个友方单位的生命',
  },
  {
    name: '角峰',
    pic: ['Yak-1.png', 'Yak-3.png', 'Yak-summer-1.png'],
    alt: 'Matterhorn',
    logo: 'logo_kjerag',
    job: '重装',
    num: 'JC03',
    r: 4,
    pool: 3,
    sex: 1,
    tags: ['近战位', '防护'],
    desc: '能够阻挡三个敌人',
  },
  {
    name: '蛇屠箱',
    pic: ['Snakek-1.png', 'Snakek-3.png', 'Snakek-wild-1.png'],
    alt: 'Cuora',
    logo: 'logo_rhodes',
    job: '重装',
    num: 'IU05',
    r: 4,
    pool: 3,
    sex: 0,
    tags: ['近战位', '防护'],
    desc: '能够阻挡三个敌人',
  },
  {
    name: '古米',
    pic: ['Sunbr-1.png', 'Sunbr-3.png', 'Sunbr-summer-1.png'],
    alt: 'Гум',
    logo: 'logo_ursus',
    job: '重装',
    num: 'USS3',
    r: 4,
    pool: 3,
    sex: 0,
    tags: ['近战位', '防护', '治疗'],
    desc: '技能可以治疗友方单位',
  },
  {
    name: '坚雷',
    pic: ['Durnar-1.png', 'Durnar-3.png'],
    alt: 'Dur-nar',
    logo: 'logo_rhodes',
    job: '重装',
    num: 'R124',
    r: 4,
    pool: 4,
    sex: 0,
    tags: ['近战位', '防护', '输出'],
    desc: '技能开启时普通攻击会造成法术伤害',
  },
  {
    name: '深海色',
    pic: ['Deepcl-1.png', 'Deepcl-3.png'],
    alt: 'Deepcolor',
    logo: 'logo_rhodes',
    job: '辅助',
    num: 'AA04',
    r: 4,
    pool: 1,
    sex: 0,
    tags: ['远程位', '召唤'],
    desc: '攻击造成<@ba.kw>法术伤害</>\n可以使用<@ba.kw>召唤物</>协助作战',
  },
  {
    name: '地灵',
    pic: ['Skgoat-1.png', 'Skgoat-3.png'],
    alt: 'Earthspirit',
    logo: 'logo_Leithanien',
    job: '辅助',
    num: 'LN01',
    r: 4,
    pool: 3,
    sex: 0,
    tags: ['远程位', '减速'],
    desc: '攻击造成<@ba.kw>法术伤害</>，并对敌人造成短暂的<@ba.kw>停顿</>',
  },
  {
    name: '阿消',
    pic: ['Sqrrel-1.png', 'Sqrrel-3.png'],
    alt: 'Shaw',
    logo: 'logo_lungmen',
    job: '特种',
    num: 'LM11',
    r: 4,
    pool: 3,
    sex: 0,
    tags: ['近战位', '位移'],
    desc: '同时攻击阻挡的<@ba.kw>所有敌人</>\n可以放置于远程位',
  },
  {
    name: '白面鸮',
    pic: ['Plosis-1.png', 'Plosis-3.png'],
    alt: 'Ptilopsis',
    logo: 'logo_rhine',
    job: '医疗',
    num: 'RL04',
    r: 5,
    pool: 3,
    sex: 0,
    tags: ['远程位', '治疗', '支援'],
    desc: '同时恢复三个友方单位的生命',
  },
  {
    name: '凛冬',
    pic: ['Headbr-1.png', 'Headbr-3.png'],
    alt: 'Зима',
    logo: 'logo_ursus',
    job: '先锋',
    num: 'USS1',
    r: 5,
    pool: 3,
    sex: 0,
    tags: ['近战位', '费用回复', '支援'],
    desc: '能够阻挡两个敌人',
  },
  {
    name: '德克萨斯',
    pic: ['Texas-1.png', 'Texas-3.png', 'Texas-winter-1.png'],
    alt: 'Texas',
    logo: 'logo_penguin',
    job: '先锋',
    num: 'PL02',
    r: 5,
    pool: 3,
    sex: 0,
    tags: ['近战位', '费用回复', '控场'],
    desc: '能够阻挡两个敌人',
  },
  {
    name: '诗怀雅',
    pic: ['Swire-1.png', 'Swire-3.png'],
    alt: 'Swire',
    logo: 'logo_lungmen',
    job: '近卫',
    num: 'LM08',
    r: 5,
    pool: 1,
    sex: 0,
    tags: ['近战位', '输出', '支援'],
    desc: '可以攻击到<@ba.kw>较远敌人</>',
  },
  {
    name: '芙兰卡',
    pic: ['Franka-1.png', 'Franka-3.png'],
    alt: 'Franka',
    logo: 'logo_blacksteel',
    job: '近卫',
    num: 'BS01',
    r: 5,
    pool: 1,
    sex: 0,
    tags: ['近战位', '输出', '生存'],
    desc: '能够阻挡一个敌人',
  },
  {
    name: '炎客',
    pic: ['Flameb-1.png', 'Flameb-3.png'],
    alt: 'Flamebringer',
    logo: 'logo_rhodes',
    job: '近卫',
    num: 'R137',
    r: 5,
    pool: 4,
    sex: 1,
    tags: ['近战位', '输出', '生存'],
    desc: '能够阻挡一个敌人',
  },
  {
    name: '因陀罗',
    pic: ['Tiger-1.png', 'Tiger-3.png'],
    alt: 'Indra',
    logo: 'logo_victoria',
    job: '近卫',
    num: 'GG03',
    r: 5,
    pool: 2,
    sex: 0,
    tags: ['近战位', '输出', '生存'],
    desc: '能够阻挡一个敌人',
  },
  {
    name: '拉普兰德',
    pic: ['Whitew-1.png', 'Whitew-3.png'],
    alt: 'Lappland',
    logo: 'logo_rhodes',
    job: '近卫',
    num: 'SR01',
    r: 5,
    pool: 1,
    sex: 0,
    tags: ['近战位', '输出', '削弱'],
    desc: '可以进行<@ba.kw>远程攻击</>，但此时攻击力降低至80%',
  },
  {
    name: '幽灵鲨',
    pic: ['Ghost-1.png', 'Ghost-3.png', 'Ghost-winter-1.png'],
    alt: 'Specter',
    logo: 'logo_abyssal',
    job: '近卫',
    num: 'AA02',
    r: 5,
    pool: 3,
    sex: 0,
    tags: ['近战位', '群攻', '生存'],
    desc: '同时攻击阻挡的<@ba.kw>所有敌人</>',
  },
  {
    name: '星极',
    pic: ['Astesi-1.png', 'Astesi-3.png'],
    alt: 'Astesia',
    logo: 'logo_rhodes',
    job: '近卫',
    num: 'RR01',
    r: 5,
    pool: 1,
    sex: 0,
    tags: ['近战位', '输出', '防护'],
    desc: '攻击造成<@ba.kw>法术伤害</>',
  },
  {
    name: '蓝毒',
    pic: ['Bluep-1.png', 'Bluep-3.png'],
    alt: 'Blue Poison',
    logo: 'logo_rhodes',
    job: '狙击',
    num: 'AA03',
    r: 5,
    pool: 3,
    sex: 0,
    tags: ['远程位', '输出'],
    desc: '优先攻击空中单位',
  },
  {
    name: '白金',
    pic: ['Platnm-1.png', 'Platnm-3.png'],
    alt: 'Platinum',
    logo: 'logo_kazimierz',
    job: '狙击',
    num: 'KZ03',
    r: 5,
    pool: 3,
    sex: 0,
    tags: ['远程位', '输出'],
    desc: '优先攻击空中单位',
  },
  {
    name: '陨星',
    pic: ['Meteo-1.png', 'Meteo-3.png', 'Meteo-sweep-1.png'],
    alt: 'Meteorite',
    logo: 'logo_rhodes',
    job: '狙击',
    num: 'ST03',
    r: 5,
    pool: 3,
    sex: 0,
    tags: ['远程位', '群攻', '削弱'],
    desc: '攻击造成<@ba.kw>群体物理伤害</>',
  },
  {
    name: '送葬人',
    pic: ['Excu-1.png', 'Excu-3.png'],
    alt: 'Executor',
    logo: 'logo_Laterano',
    job: '狙击',
    num: 'LT01',
    r: 5,
    pool: 1,
    sex: 1,
    tags: ['远程位', '群攻'],
    desc: '攻击范围内的<@ba.kw>所有敌人</>，对自己前方一横排的敌人攻击力提升至150%',
  },
  {
    name: '阿米娅',
    pic: ['Amiya-1.png', 'Amiya-2.png', 'Amiya-3.png', 'Amiya-winter-1.png'],
    alt: 'Amiya',
    logo: 'logo_rhodes',
    job: '术师',
    num: 'R001',
    r: 5,
    pool: 4,
    sex: 0,
    tags: ['远程位', '输出'],
    desc: '攻击造成<@ba.kw>法术伤害</>',
  },
  {
    name: '天火',
    pic: ['Skfire-1.png', 'Skfire-3.png', 'Skfire-summer-1.png'],
    alt: 'Skyfire',
    logo: 'logo_rhodes',
    job: '术师',
    num: 'SK01',
    r: 5,
    pool: 1,
    sex: 0,
    tags: ['远程位', '群攻', '控场'],
    desc: '攻击造成<@ba.kw>群体法术伤害</>',
  },
  {
    name: '梅尔',
    pic: ['Otter-1.png', 'Otter-3.png'],
    alt: 'Mayer',
    logo: 'logo_rhine',
    job: '辅助',
    num: 'RL05',
    r: 5,
    pool: 3,
    sex: 0,
    tags: ['远程位', '召唤', '控场'],
    desc: '攻击造成<@ba.kw>法术伤害</>\n可以使用<@ba.kw>召唤物</>协助作战',
  },
  {
    name: '赫默',
    pic: ['Silent-1.png', 'Silent-3.png', 'Silent-sweep-1.png'],
    alt: 'Silence',
    logo: 'logo_rhine',
    job: '医疗',
    num: 'RL01',
    r: 5,
    pool: 3,
    sex: 0,
    tags: ['远程位', '治疗'],
    desc: '恢复友方单位生命',
  },
  {
    name: '华法琳',
    pic: ['Bldsk-1.png', 'Bldsk-3.png'],
    alt: 'Warfarin',
    logo: 'logo_rhodes',
    job: '医疗',
    num: 'R106',
    r: 5,
    pool: 3,
    sex: 0,
    tags: ['远程位', '治疗', '支援'],
    desc: '恢复友方单位生命',
  },
  {
    name: '锡兰',
    pic: ['Ceylon-1.png', 'Ceylon-3.png'],
    alt: 'Ceylon',
    logo: 'logo_siesta',
    job: '医疗',
    num: 'SS01',
    r: 5,
    pool: 4,
    sex: 0,
    tags: ['远程位', '治疗'],
    desc: '拥有较大治疗范围，但在治疗较远目标时治疗量变为<@ba.kw>{heal_scale:0%}</>',
  },
  {
    name: '临光',
    pic: ['Nearl-1.png', 'Nearl-3.png'],
    alt: 'Nearl',
    logo: 'logo_rhodes',
    job: '重装',
    num: 'FO02',
    r: 5,
    pool: 3,
    sex: 0,
    tags: ['近战位', '防护', '治疗'],
    desc: '技能可以治疗友方单位',
  },
  {
    name: '红',
    pic: ['Red-1.png', 'Red-3.png'],
    alt: 'Projekt Red',
    logo: 'logo_rhodes',
    job: '特种',
    num: 'SW01',
    r: 5,
    pool: 3,
    sex: 0,
    tags: ['近战位', '快速复活', '控场'],
    desc: '再部署时间大幅度<@ba.kw>减少</>',
  },
  {
    name: '雷蛇',
    pic: ['Liskam-1.png', 'Liskam-3.png'],
    alt: 'Liskarm',
    logo: 'logo_blacksteel',
    job: '重装',
    num: 'BS02',
    r: 5,
    pool: 3,
    sex: 0,
    tags: ['近战位', '防护', '输出'],
    desc: '能够阻挡三个敌人',
  },
  {
    name: '可颂',
    pic: ['Moeshd-1.png', 'Moeshd-3.png'],
    alt: 'Croissant',
    logo: 'logo_penguin',
    job: '重装',
    num: 'PL04',
    r: 5,
    pool: 3,
    sex: 0,
    tags: ['近战位', '防护', '位移'],
    desc: '能够阻挡三个敌人',
  },
  {
    name: '火神',
    pic: ['Hpsts-1.png', 'Hpsts-3.png'],
    alt: 'Vulcan',
    logo: 'logo_rhodes',
    job: '重装',
    num: 'MN02',
    r: 5,
    pool: 2,
    sex: 0,
    tags: ['近战位', '生存', '防护', '输出'],
    desc: '<@ba.kw>无法</>被友方角色治疗',
  },
  {
    name: '普罗旺斯',
    pic: ['Prove-1.png', 'Prove-3.png'],
    alt: 'Provence',
    logo: 'logo_rhodes',
    job: '狙击',
    num: 'SR03',
    r: 5,
    pool: 3,
    sex: 0,
    tags: ['远程位', '输出'],
    desc: '高精度的近距离射击',
  },
  {
    name: '守林人',
    pic: ['Milu-1.png', 'Milu-3.png'],
    alt: 'Firewatch',
    logo: 'logo_rhodes',
    job: '狙击',
    num: 'ST01',
    r: 5,
    pool: 3,
    sex: 0,
    tags: ['远程位', '输出', '爆发'],
    desc: '优先攻击攻击范围内<@ba.kw>防御力最低</>的敌方单位',
  },
  {
    name: '崖心',
    pic: ['Slchan-1.png', 'Slchan-3.png', 'Slchan-wild-1.png'],
    alt: 'Cliffheart',
    logo: 'logo_kjerag',
    job: '特种',
    num: 'JC06',
    r: 5,
    pool: 3,
    sex: 0,
    tags: ['近战位', '位移', '输出'],
    desc: '技能可以使敌人产生<@ba.kw>位移</>\n可以放置于远程位',
  },
  {
    name: '初雪',
    pic: ['Slbell-1.png', 'Slbell-3.png'],
    alt: 'Pramanix',
    logo: 'logo_kjerag',
    job: '辅助',
    num: 'JC05',
    r: 5,
    pool: 3,
    sex: 0,
    tags: ['远程位', '削弱'],
    desc: '攻击造成<@ba.kw>法术伤害</>',
  },
  {
    name: '真理',
    pic: ['Glassb-1.png', 'Glassb-3.png'],
    alt: 'Истина',
    logo: 'logo_ursus',
    job: '辅助',
    num: 'USS2',
    r: 5,
    pool: 3,
    sex: 0,
    tags: ['远程位', '减速', '输出'],
    desc: '攻击造成<@ba.kw>法术伤害</>，并对敌人造成短暂的<@ba.kw>停顿</>',
  },
  {
    name: '格劳克斯',
    pic: ['Glacus-1.png', 'Glacus-3.png'],
    alt: 'Glaucus',
    logo: 'logo_rhodes',
    job: '辅助',
    num: 'R128',
    r: 5,
    pool: 1,
    sex: 0,
    tags: ['远程位', '减速', '控场'],
    desc: '攻击造成<@ba.kw>法术伤害</>，并对敌人造成短暂的<@ba.kw>停顿</>',
  },
  {
    name: '空',
    pic: ['Sora-1.png', 'Sora-3.png', 'Sora-summer-1.png'],
    alt: 'Sora',
    logo: 'logo_penguin',
    job: '辅助',
    num: 'PL05',
    r: 5,
    pool: 1,
    sex: 0,
    tags: ['远程位', '支援', '治疗'],
    desc: '不进行攻击，持续恢复攻击范围内所有友军的<@ba.kw>生命</>（每秒恢复相当于空攻击力10%的生命）',
  },
  {
    name: '狮蝎',
    pic: ['Mantic-1.png', 'Mantic-3.png'],
    alt: 'Manticore',
    logo: 'logo_rhodes',
    job: '特种',
    num: 'SG01',
    r: 5,
    pool: 3,
    sex: 0,
    tags: ['近战位', '输出', '生存'],
    desc: '对攻击范围内<@ba.kw>所有敌人</>造成伤害\n拥有50%的物理和法术闪避且不容易成为敌人的<@ba.kw>攻击目标</>',
  },
  {
    name: '食铁兽',
    pic: ['Panda-1.png', 'Panda-3.png'],
    alt: 'FEater',
    logo: 'logo_rhodes',
    job: '特种',
    num: 'YD01',
    r: 5,
    pool: 3,
    sex: 0,
    tags: ['近战位', '位移', '减速'],
    desc: '同时攻击阻挡的<@ba.kw>所有敌人</>\n可以放置于远程位',
  },
  {
    name: '能天使',
    pic: ['Angel-1.png', 'Angel-3.png', 'Angel-wild-1.png'],
    alt: 'Exusiai',
    logo: 'logo_penguin',
    job: '狙击',
    num: 'PL03',
    r: 6,
    pool: 3,
    sex: 0,
    tags: ['远程位', '输出'],
    desc: '优先攻击空中单位',
  },
  {
    name: '黑',
    pic: ['Shwaz-1.png', 'Shwaz-3.png'],
    alt: 'Schwarz',
    logo: 'logo_siesta',
    job: '狙击',
    num: 'SS02',
    r: 6,
    pool: 1,
    sex: 0,
    tags: ['远程位', '输出'],
    desc: '高精度的近距离射击',
  },
  {
    name: '推进之王',
    pic: ['Siege-1.png', 'Siege-3.png'],
    alt: 'Siege',
    logo: 'logo_victoria',
    job: '先锋',
    num: 'GG01',
    r: 6,
    pool: 3,
    sex: 0,
    tags: ['近战位', '费用回复', '输出'],
    desc: '能够阻挡两个敌人',
  },
  {
    name: '伊芙利特',
    pic: ['Ifrit-1.png', 'Ifrit-3.png', 'Ifrit-summer-1.png'],
    alt: 'Ifrit',
    logo: 'logo_rhine',
    job: '术师',
    num: 'RL03',
    r: 6,
    pool: 3,
    sex: 0,
    tags: ['远程位', '群攻', '削弱'],
    desc: '攻击造成<@ba.kw>超远距离的群体法术伤害</>',
  },
  {
    name: '艾雅法拉',
    pic: ['Amgoat-1.png', 'Amgoat-3.png'],
    alt: 'Eyjafjalla',
    logo: 'logo_Leithanien',
    job: '术师',
    num: 'LN02',
    r: 6,
    pool: 1,
    sex: 0,
    tags: ['远程位', '输出', '削弱'],
    desc: '攻击造成<@ba.kw>法术伤害</>',
  },
  {
    name: '安洁莉娜',
    pic: ['Aglina-1.png', 'Aglina-3.png'],
    alt: 'Angelina',
    logo: 'logo_rhodes',
    job: '辅助',
    num: 'SR02',
    r: 6,
    pool: 1,
    sex: 0,
    tags: ['远程位', '减速', '输出', '支援'],
    desc: '攻击造成<@ba.kw>法术伤害</>，并对敌人造成短暂的<@ba.kw>停顿</>',
  },
  {
    name: '麦哲伦',
    pic: ['Mgllan-1.png', 'Mgllan-3.png'],
    alt: 'Magallan',
    logo: 'logo_rhine',
    job: '辅助',
    num: 'RL06',
    r: 6,
    pool: 1,
    sex: 0,
    tags: ['远程位', '支援', '减速', '输出'],
    desc: '攻击造成<@ba.kw>法术伤害</>\n可以使用<@ba.kw>召唤物</>协助作战',
  },
  {
    name: '闪灵',
    pic: ['Shining-1.png', 'Shining-3.png', 'Shining-summer-1.png'],
    alt: 'Shining',
    logo: 'logo_rhodes',
    job: '医疗',
    num: 'FO01',
    r: 6,
    pool: 3,
    sex: 0,
    tags: ['远程位', '治疗', '支援'],
    desc: '恢复友方单位生命',
  },
  {
    name: '夜莺',
    pic: ['Cgbird-1.png', 'Cgbird-3.png'],
    alt: 'Nightingale',
    logo: 'logo_rhodes',
    job: '医疗',
    num: 'FO03',
    r: 6,
    pool: 3,
    sex: 0,
    tags: ['远程位', '治疗', '支援'],
    desc: '同时恢复三个友方单位的生命',
  },
  {
    name: '星熊',
    pic: ['Hsguma-1.png', 'Hsguma-3.png'],
    alt: 'Hoshiguma',
    logo: 'logo_lungmen',
    job: '重装',
    num: 'LM05',
    r: 6,
    pool: 3,
    sex: 0,
    tags: ['近战位', '防护', '输出'],
    desc: '能够阻挡三个敌人',
  },
  {
    name: '塞雷娅',
    pic: ['Demkni-1.png', 'Demkni-3.png'],
    alt: 'Saria',
    logo: 'logo_rhine',
    job: '重装',
    num: 'RL02',
    r: 6,
    pool: 3,
    sex: 0,
    tags: ['近战位', '防护', '治疗', '支援'],
    desc: '技能可以治疗友方单位',
  },
  {
    name: '银灰',
    pic: ['Svrash-1.png', 'Svrash-3.png'],
    alt: 'SilverAsh',
    logo: 'logo_kjerag',
    job: '近卫',
    num: 'JC01',
    r: 6,
    pool: 3,
    sex: 1,
    tags: ['近战位', '输出', '支援'],
    desc: '可以进行<@ba.kw>远程攻击</>，但此时攻击力降低至80%',
  },
  {
    name: '陈',
    pic: ['Chen-1.png', 'Chen-3.png'],
    alt: "Ch'en",
    logo: 'logo_lungmen',
    job: '近卫',
    num: 'LM04',
    r: 6,
    pool: 1,
    sex: 0,
    tags: ['近战位', '爆发', '输出'],
    desc: '普通攻击连续造成<@ba.kw>两次</>伤害',
  },
  {
    name: '赫拉格',
    pic: ['Helage-1.png', 'Helage-3.png'],
    alt: 'Hellagur',
    logo: 'logo_rhodes',
    job: '近卫',
    num: 'AZ01',
    r: 6,
    pool: 1,
    sex: 1,
    tags: ['近战位', '输出', '生存'],
    desc: '不成为其他角色的治疗目标，每次攻击到敌人后回复自身<@ba.kw>{value}</>生命',
  },
  {
    name: '暴行',
    pic: ['Savage-1.png', 'Savage-3.png'],
    alt: 'Savage',
    logo: 'logo_rim',
    job: '近卫',
    num: 'RB01',
    r: 5,
    pool: 4,
    sex: 0,
    tags: ['近战位', '群攻', '爆发'],
    desc: '同时攻击阻挡的<@ba.kw>所有敌人</>',
  },
  {
    name: '空爆',
    pic: ['Catap-1.png'],
    alt: 'Catapult',
    logo: 'logo_rhodes',
    job: '狙击',
    num: 'PA63',
    r: 3,
    pool: 1,
    sex: 0,
    tags: ['远程位', '群攻'],
    desc: '攻击造成<@ba.kw>群体物理伤害</>',
  },
  {
    name: '月见夜',
    pic: ['Midn-1.png'],
    alt: 'Midnight',
    logo: 'logo_rhodes',
    job: '近卫',
    num: 'PA62',
    r: 3,
    pool: 1,
    sex: 1,
    tags: ['近战位', '输出'],
    desc: '可以进行<@ba.kw>远程攻击</>，但此时攻击力降低至80%',
  },
  {
    name: '猎蜂',
    pic: ['Brownb-1.png', 'Brownb-3.png'],
    alt: 'Beehunter',
    logo: 'logo_ursus',
    job: '近卫',
    num: 'US10',
    r: 4,
    pool: 1,
    sex: 0,
    tags: ['近战位', '输出'],
    desc: '能够阻挡一个敌人',
  },
  {
    name: '夜魔',
    pic: ['Nightm-1.png', 'Nightm-3.png'],
    alt: 'Nightmare',
    logo: 'logo_victoria',
    job: '术师',
    num: 'VC03',
    r: 5,
    pool: 1,
    sex: 0,
    tags: ['远程位', '输出', '治疗', '减速'],
    desc: '攻击造成<@ba.kw>法术伤害</>',
  },
  {
    name: '格拉尼',
    pic: ['Grani-1.png', 'Grani-3.png'],
    alt: 'Grani',
    logo: 'logo_victoria',
    job: '先锋',
    num: 'VC05',
    r: 5,
    pool: 4,
    sex: 0,
    tags: ['近战位', '费用回复', '防护'],
    desc: '击杀敌人后获得1点部署费用，撤退时返还初始部署费用',
  },
  {
    name: '斯卡蒂',
    pic: ['Skadi-1.png', 'Skadi-3.png'],
    alt: 'Skadi',
    logo: 'logo_abyssal',
    job: '近卫',
    num: 'AA01',
    r: 6,
    pool: 1,
    sex: 0,
    tags: ['近战位', '输出', '生存'],
    desc: '能够阻挡一个敌人',
  },
];
